application:
  name: adilApp

server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-3.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.piapixhkrfyuyhpreeae
    password: P@s$7gXv!a92LzrT
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 30000
  sql:
    init:
      mode: never
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    schemas: public
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: myVerySecretKeyThatIsAtLeast32CharactersLongForHMAC256Algorithm
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always